//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angular
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public long Phone { get; set; }
        public string Department { get; set; }
        public double Salary { get; set; }
        public string EmailID { get; set; }
    }
}
