//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarang
{
    using System;
    using System.Collections.Generic;
    
    public partial class BDskill
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string EmailID { get; set; }
        public System.DateTime DOB { get; set; }
        public string ProfilePath { get; set; }
        public string Password { get; set; }
    }
}
