//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bio
    {
        public long ID { get; set; }
        public string Address { get; set; }
        public long PhoneNumber { get; set; }
        public string Certificate { get; set; }
    }
}
