//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarang
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chart_tbl
    {
        public int Stateid { get; set; }
        public string StateName { get; set; }
        public int Male { get; set; }
        public int Female { get; set; }
    }
}
