//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarang
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAddress
    {
        public long AddressId { get; set; }
        public string Colony { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public long Userid { get; set; }
    }
}
