//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sarang
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOrder
    {
        public int OrderId { get; set; }
        public string ItemName { get; set; }
        public string PaymentType { get; set; }
        public long Price { get; set; }
        public long Userid { get; set; }
    }
}
